// MCP Server — MCP Server Web Scraper Kit (TypeScript) · auto-generated by PixHarvest company brain
// 用法: 部署到 Cloudflare Workers，作为 MCP 客户端(Claude/Cursor)的 server 端点
export default {
  async fetch(request) {
    const body = await request.json().catch(() => ({}));
    if (body.method === "initialize") {
      return json({ protocolVersion: "2025-03-26", capabilities: { tools: {} },
        serverInfo: { name: "mcp-web-scraper", version: "1.0.0" } });
    }
    if (body.method === "tools/list") {
      return json({ tools: [{"name": "echo", "description": "Echo back the input text", "inputSchema": {"type": "object", "properties": {"text": {"type": "string"}}}}, {"name": "now", "description": "Get current UTC time", "inputSchema": {"type": "object", "properties": {}}}, {"name": "gen_uuid", "description": "Generate a UUID v4", "inputSchema": {"type": "object", "properties": {}}}] });
    }
    if (body.method === "tools/call") {
      const args = body.params?.arguments || {};
      if (body.params?.name === "echo") return json({ content: [{ type: "text", text: args.text || "" }] });
      if (body.params?.name === "now") return json({ content: [{ type: "text", text: new Date().toISOString() }] });
      if (body.params?.name === "gen_uuid") return json({ content: [{ type: "text", text: crypto.randomUUID() }] });
      return json({ error: { code: -32601, message: "Tool not found" } });
    }
    return json({ error: { code: -32601, message: "Method not found" } });
  }
};
function json(o, s){ return new Response(JSON.stringify(o), { headers: { "Content-Type": "application/json" } }, status: s || 200); }
